-- ==============================================================================
-- ENTRYPOINT: Cathedra Colorscheme
-- DESCRIPTION: The native Neovim invocation target. Clears existing visual state,
-- forces True Color mode, and attempts to load the ultra-fast compiler cache.
-- Orchestrates the full specification generation upon a cache miss.
-- ==============================================================================

-- 1. State Sanitization
vim.cmd("hi clear")
if vim.fn.exists("syntax_on") then
	vim.cmd("syntax reset")
end

vim.g.colors_name = "cathedra"
vim.o.termguicolors = true

-- 2. Engine Dependencies
local compiler = require("summa.compiler")
local summa = require("summa")
local palette = require("summa.palette").colors
local editor = require("summa.highlights.editor")

local config = summa.get_config()

-- 3. Apply Global Directives (Bypassing Compiler)
-- Executed unconditionally as these are not highlight groups.
editor.set_term_colors(palette, config)

-- 4. Bytecode Cache Execution
if not compiler.load() then
	-- CACHE MISS: Generate the full specification dictionary and compile it.
	local spec = {}

	-- Merge native editor highlights
	for hl_group, hl_def in pairs(editor.get(palette, config)) do
		spec[hl_group] = hl_def
	end

	-- In subsequent phases, we will append Treesitter and Plugin syntax here:
	-- spec = vim.tbl_extend("force", spec, require("summa.highlights.syntax").get(palette))
	-- spec = vim.tbl_extend("force", spec, require("summa.highlights.plugins").get(palette, config))
    spec = vim.tbl_extend("force", spec, require("summa.highlights.syntax").get(palette))
    spec = vim.tbl_extend("force", spec, require("summa.highlights.plugins").get(palette, config))

	-- Trigger the high-performance compiler
	compiler.compile(spec)

	-- Load the newly generated bytecode chunk
	compiler.load()
end
