-- ==============================================================================
-- MODULE: Vitrea Bytecode Compiler
-- DESCRIPTION: The performance heart of the engine. Translates the merged
-- highlight matrix and global variables into a static Lua file.
-- ==============================================================================

local M = {}
local CACHE_DIR = vim.fn.stdpath("cache") .. "/vitrea"

local function get_cache_path()
	local config = require("vitrea.config").options
	return string.format("%s/%s_compiled.lua", CACHE_DIR, config.style)
end

function M.purge()
	local path = get_cache_path()
	if vim.fn.filereadable(path) == 1 then
		vim.fn.delete(path)
	end
end

--- Compiles the logical matrix and global settings into a static cache.
---@param groups table The fully consolidated highlight matrix.
---@param palette table The active palette matrix for global extraction.
function M.compile(groups, palette)
	local path = get_cache_path()

	if vim.fn.isdirectory(CACHE_DIR) == 0 then
		vim.fn.mkdir(CACHE_DIR, "p")
	end

	local lines = {
		"-- ==============================================================================",
		"-- AUTOMATICALLY GENERATED BY VITREA ENGINE",
		"-- DESCRIPTION: Static bytecode cache for instantaneous loading.",
		"-- ==============================================================================",
		"local set_hl = vim.api.nvim_set_hl",
	}

	-- 1. Inject Terminal Muzzle (Global Variables)
	local terminal_globals = require("vitrea.engine.muzzle").get(palette)
	for key, hex in pairs(terminal_globals) do
		table.insert(lines, string.format('vim.g["%s"] = "%s"', key, hex))
	end

	-- 2. Inject Syntactic Highlights
	for group, opts in pairs(groups) do
		local opts_str = "{"
		for key, value in pairs(opts) do
			local val_type = type(value)
			if val_type == "string" then
				opts_str = opts_str .. key .. '="' .. value .. '",'
			elseif val_type == "boolean" or val_type == "number" then
				opts_str = opts_str .. key .. "=" .. tostring(value) .. ","
			end
		end
		opts_str = opts_str .. "}"
		table.insert(lines, string.format('set_hl(0, "%s", %s)', group, opts_str))
	end

	local file = io.open(path, "w")
	if file then
		file:write(table.concat(lines, "\n"))
		file:close()
	end
end

function M.load()
	local path = get_cache_path()
	if vim.fn.filereadable(path) == 1 then
		local chunk = loadfile(path)
		if chunk then
			chunk()
			return true
		end
	end
	return false
end

return M
