-- ==============================================================================
-- MODULE: Summa Compiler
-- DESCRIPTION: High-performance bytecode caching engine. Translates dynamic
-- Lua tables into static, pre-calculated Neovim API calls to guarantee
-- sub-millisecond startup times.
-- ==============================================================================

local M = {}

-- Determines the exact cache path using Neovim's standard runtime directories.
local CACHE_DIR = vim.fn.stdpath("cache") .. "/summa"
local CACHE_FILE = CACHE_DIR .. "/cathedra.lua"

-- ==============================================================================
-- INTERNAL UTILITIES
-- ==============================================================================

--- Ensures the cache directory exists on the filesystem.
local function ensure_dir()
	if vim.fn.isdirectory(CACHE_DIR) == 0 then
		vim.fn.mkdir(CACHE_DIR, "p")
	end
end

--- Serializes a single highlight definition into a raw string format.
--- Escapes string values and converts booleans/numbers properly.
---@param group string The highlight group name.
---@param opts table The highlight parameters (fg, bg, bold, etc.).
---@return string? The serialized Neovim API call.
local function serialize_hl(group, opts)
	if type(opts) ~= "table" then
		return nil
	end

	local props = {}
	for key, value in pairs(opts) do
		local val_type = type(value)
		if val_type == "string" then
			table.insert(props, string.format("%s='%s'", key, value))
		elseif val_type == "boolean" or val_type == "number" then
			table.insert(props, string.format("%s=%s", key, tostring(value)))
		end
	end

	-- Handle cleared groups (e.g., forcing a transparent background explicitly)
	if #props == 0 then
		return string.format("  set_hl(0, '%s', {})", group)
	end

	return string.format("  set_hl(0, '%s', {%s})", group, table.concat(props, ", "))
end

-- ==============================================================================
-- PUBLIC API
-- ==============================================================================

--- Compiles the provided specification into a static Lua file.
--- This eradicates runtime computation during subsequent editor startups.
---@param spec table The full highlight specification containing all groups.
function M.compile(spec)
	ensure_dir()

	local file = io.open(CACHE_FILE, "w")
	if not file then
		vim.notify("[Summa] CRITICAL ERROR: Failed to write cache file to " .. CACHE_FILE, vim.log.levels.ERROR)
		return
	end

	-- Construct the static Lua script framework
	local lines = {
		"-- ====================================================================",
		"-- AUTO-GENERATED BY SUMMA COMPILER. DO NOT EDIT DIRECTLY.",
		"-- ====================================================================",
		"local set_hl = vim.api.nvim_set_hl",
		"return function()",
	}

	-- Process and serialize all highlight groups defined in the spec
	for group, opts in pairs(spec) do
		local serialized = serialize_hl(group, opts)
		if serialized then
			table.insert(lines, serialized)
		end
	end

	table.insert(lines, "end")

	-- Commit to disk
	file:write(table.concat(lines, "\n"))
	file:close()
end

--- Attempts to load and execute the compiled theme from the cache.
--- Uses loadfile() to leverage LuaJIT's blazing fast chunk execution.
---@return boolean true if successfully loaded and applied, false otherwise.
function M.load()
	local cached_chunk = loadfile(CACHE_FILE)
	if cached_chunk then
		local apply_theme = cached_chunk()
		if type(apply_theme) == "function" then
			apply_theme()
			return true
		end
	end
	return false
end

return M
